
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1/entregas?createDatabaseIfNotExist=true&timeZone=UTC
    #    url: jdbc:mysql://localhost/entregas-api?createDatabaseIfNotExist=true&timeZone=UTC
    username: root
    password: Password123#@!
  #    url: jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=localhost)(PORT=1521)))(CONNECT_DATA=(SERVICE_NAME=XEPDB1)))
  #    username: TESTE
  #    password: TESTE
  #    driver-class-name: oracle.jdbc.OracleDriver


  jpa:
    hibernate:
      gerenate-ddl: true
      ddl-auto: create
    #      ddl-auto: update

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect # depende da versão do java
        show_sql: true
        format_sql: true
      ##      hibernate.dialect: org.hibernate.dialect.OracleDialect # depende da versão do java
      #      hibernate.show_sql: true
      #      hibernate.format_sql: true
      # Além de verificar as permissão necessárias de usuário no banco no caso Oracle XE...



